Repository SoftEng-HEIGVD/Teaching-HEIGVD-RES-2021-Chill, pull requests merged in 2021-03, with the labels that each got.

#203 Add Barbar with tests
  src/main/java/ch/heigvd/res/chill/domain/CarlP97/Barbar.java
  src/test/java/ch/heigvd/res/chill/domain/CarlP97/BarbarTest.java
Labels: enhancement

#232 Add Cidre with tests
  src/main/java/ch/heigvd/res/chill/domain/jadegrli/Cidre.java
  src/test/java/ch/heigvd/res/chill/domain/jadegrli/CidreTest.java
Labels: enhancement

#227 Poretti6 beer
  src/main/java/ch/heigvd/res/chill/domain/Alessandro_AP/Poretti6.java
  src/test/java/ch/heigvd/res/chill/domain/Alessandro_AP/Poretti6Test.java
Labels: enhancement

#221 Limoncello liqueur
  src/main/java/ch/heigvd/res/chill/domain/Alessandro_AP/Limoncello.java
  src/test/java/ch/heigvd/res/chill/domain/Alessandro_AP/LimoncelloTest.java
Labels: enhancement

#192 Add ClubMate
  src/main/java/ch/heigvd/res/chill/domain/jadegrli/ClubMate.java
  src/test/java/ch/heigvd/res/chill/domain/jadegrli/ClubMateTest.java
Labels: enhancement

#278 Adding beer : Prix Garantie + test
  src/main/java/ch/heigvd/res/chill/domain/AllemanoEn/PrixGarantie.java
  src/test/java/ch/heigvd/res/chill/domain/AllemanoEn/PrixGarantieTest.java
Labels: enhancement

#216 add new drink PepsiMax with test
  src/main/java/ch/heigvd/res/chill/domain/gabthr/PepsiMax.java
  src/test/java/ch/heigvd/res/chill/domain/gabthr/PepsiMaxTest.java
Labels: enhancement

#201 Add new beer Chopfab with test
  src/main/java/ch/heigvd/res/chill/domain/gabthr/Chopfab.java
  src/test/java/ch/heigvd/res/chill/domain/gabthr/ChopfabTest.java
Labels: enhancement

#294 Add Grimbergen with tests
  src/main/java/ch/heigvd/res/chill/domain/noahfusi/Grimbergen.java
  src/test/java/ch/heigvd/res/chill/domain/noahfusi/GrimbergenTest.java
Labels: enhancement

#109 Add Swaf with tests
  src/main/java/ch/heigvd/res/chill/domain/maxscharwath/Swaf.java
  src/test/java/ch/heigvd/res/chill/domain/maxscharwath/SwafTest.java
Labels: invalid

#214 Fb sagres
  src/main/java/ch/heigvd/res/chill/domain/DSDaniel/Sagres.java
  src/test/java/ch/heigvd/res/chill/domain/DSDaniel/SagresTest.java
Labels: Too many files

#304 Add Lowenbrau with tests
  src/main/java/ch/heigvd/res/chill/domain/yanik23/Lowenbrau.java
  src/test/java/ch/heigvd/res/chill/domain/yanik23/LowenbrauTest.java
Labels: enhancement

#303 Add Delirium with tests
  src/main/java/ch/heigvd/res/chill/domain/hakimderder/Delirium.java
  src/test/java/ch/heigvd/res/chill/domain/hakimderder/DeliriumTest.java
Labels: enhancement

#308 Add Malandrin to the menu with tests
  src/main/java/ch/heigvd/res/chill/domain/jlheig/Malandrin.java
  src/test/java/ch/heigvd/res/chill/domain/jlheig/MalandrinTest.java
Labels: enhancement
